name: Build Test & Dry Run

on:
  push:
    branches:
      - main
      - contrib
      - indev

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: CMake build
        run: |
          cd build
          cmake -DINCLUDE_SDL:BOOL=OFF ..
          make -j
      - name: Dry run
        run: |
          cd build
          cd bin
          ./greave -dry-run

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: CMake build
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -G"MinGW Makefiles" ..
          make -j
